# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j5lteub/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/keymaste.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/keymaste.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/keymaste.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/keymaste.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/keymaste.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/widevine.b00:system/vendor/firmware/widevine.b00 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/widevine.b01:system/vendor/firmware/widevine.b01 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/widevine.b02:system/vendor/firmware/widevine.b02 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/widevine.b03:system/vendor/firmware/widevine.b03 \
    vendor/samsung/j5lteub/proprietary/vendor/firmware/widevine.mdt:system/vendor/firmware/widevine.mdt \
    vendor/samsung/j5lteub/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/j5lteub/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/j5lteub/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/j5lteub/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/j5lteub/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/j5lteub/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/j5lteub/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/j5lteub/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so
